version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "contact-form-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vfjnyf6hjhoo"
s3_prefix = "contact-form-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DynamoDBTableStreamARN=\"arn:aws:dynamodb:us-east-1:901775600839:table/formtable-dev/stream/2021-02-10T04:19:44.382\" FromMailIdentityName=\"matheusgmcm+from@gmail.com\" ToMailIdentityName=\"matheusgmcm+to@gmail.com\""
